db.getCollection("test2").find({})
db.test2.insert({name:"小海",age:30})
db.test2.insert({name:"小海",age:30})
db.test2.insert([{name:"小海",age:20},{name:"哈哈",age:39}])
db.test2.insert([{name:"老海",age:59},{name:"老红",age:58}])
db.test2.find()
//查询age值为20的文档对象
db.test2.find({age:20})
//查询age为20,name为小红的对象
db.test2.find({age:20,name:"小红"})
//查找age为20和30的对象
db.test2.find({age:{$in:[20,30]}})
//使用$or模拟$in.查找年龄为20和30的数据
db.test2.find({$or:[{age:20},{age:30}]})
//查询age不为20和不为30的文档对象
db.test2.find({age:{$nin:[20,30]}})
db.test2.find()
//查询name为小海的或者age为20的文档对象
db.test2.find({$or:[{age:20},{name:"小海"}]})
//查询name为小红而且年龄为20的文档对象
db.test2.find({$and:[{name:"小红"},{age:20}]})
//查询年龄为小于40的文档对象
db.test2.find({age:{$lt:40}})
//查询age-1之后小于38的文档对象
db.test2.find({$where:function(){ return this.age-1<38}}) 
//查询name中"哈"的文档对象
db.test2.find({name:/^哈/})
//添加一个数据
db.test2.insert({name:"小哈",age:20})
//查找数据
db.test2.find({name:/^哈/})
//查找以哈结束的文档对象
db.test2.find({name:/哈$/})

